### ISSUE TITLE
甲骨文ARM机器安装报错

### ISSUE THREAD

**Issue by TEAMO233** [hunshcn/gh-proxy#107]
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by TEAMO233** [comment]
docker run -d --name="gh-proxy-py" \
  -p 0.0.0.0:80:80 \
  --restart=always \
  hunsh/gh-proxy-py:latest
  使用的这个命令

**Comment by db-one** [comment]
![image](https://github.com/hunshcn/gh-proxy/assets/20243226/13fcdd6c-6f0d-46fc-bc51-5710f54177bc)
很明显   docker镜像仅支持X86架构的CPU

**Comment by hunshcn** [comment]
我明天构建一个吧

**Comment by hunshcn** [comment]
构建完成。测试可用。
