### ISSUE TITLE
是不是不能用了？

### ISSUE THREAD

**Issue by JackloveJam** [hunshcn/gh-proxy#111]
我在今天看到这个仓库，并在cf上部署。
经过测试下载docker-compose文件时，发现页面会跳转到 github 404提示页，并且还需要登陆。
似乎和看到很多人写的本仓库教程的下载结果完全不同。
（包括我使用作者给出的演示站，也是一样结果）

**Comment by hunshcn** [comment]
.............你少了 v。发帖前请先自我检查
