### ISSUE TITLE
用户输入链接后自动拼接成下载地址并显示到页面上，方便复制

### ISSUE THREAD

**Issue by imldy** [hunshcn/gh-proxy#112]
应用场景：命令行下载等

**Comment by xiaozhou26** [comment]
在JavaScript中，我们不能直接将数据打印到HTML文件

**Comment by hunshcn** [comment]
其实目前的设计就是为了方便你直接使用地址栏

**Comment by xiaozhou26** [comment]
> 其实目前的设计就是为了方便你直接使用地址栏，直接贴后面就好了

刚刚尝试了下js返回数据，然后html让get数据接着打印出来，似乎是行不通的，不知道大佬有没有什么方法

**Comment by imldy** [comment]
> 其实目前的设计就是为了方便你直接使用地址栏，直接贴后面就好了

感谢回复，理解了

**Comment by xiaozhou26** [comment]
建议用标准js重写，woker环境很多指令无法使用，我的开源项目https://github.com/xiaozhou26/gh-photo就是基于标准js写的，可以直接将返回链接显示到html上

**Comment by xiaozhou26** [comment]
尝试多种方法企图在woker上实现document功能，均无效，希望有大佬可以实现

**Comment by hunshcn** [comment]
> 尝试多种方法企图在woker上实现document功能，均无效，希望有大佬可以实现

........你应该在 worker js 里面 document，你应该在 worker 返回的 html 里面写 js 访问 document，你需要理解一下这两个运行环境

**Comment by xiaozhou26** [comment]
> > 尝试多种方法企图在woker上实现document功能，均无效，希望有大佬可以实现
> 
> ........你不应该在 worker js 里面 document，你应该在 worker 返回的 html 里面写 js 访问 document，你需要理解一下这两个运行环境

ok，我尝试一下
