### ISSUE TITLE
能否支持代理ipv6网站？

### ISSUE THREAD

**Issue by rodingbaba** [hunshcn/gh-proxy#115]
有个双栈的服务器，能否通过 http://ipv4+http://ipv6 的地址代理ipv6的网址

**Comment by hunshcn** [comment]
入口是你配置决定的，监听的ip或者如果更外部还有个网关，由它决定。如果希望访问 github 走 ipv6 ，可能得自己改下代码。这不是一个常用需求，并且目前处于低维护状态。

你可以参考 https://blog.csdn.net/liaoyuhang888/article/details/104041823 的最后一个 code block

**Comment by rodingbaba** [comment]
可能是描述的不对，我的需求是这样的。我有一个ipv6 的视频源，http://[2409:8087:1e03:21::2]:6060/cms001/ch00000090990000001022/index.m3u8   但是我的电视没有ipv6网络。我想的是能否通过 我的一个双栈的服务器，使用 http://22.1.1.1/http://[2409:8087:1e03:21::2]:6060/cms001/ch00000090990000001022/index.m3u8  转换这个地址给我的电视用。

**Comment by hunshcn** [comment]
额理论上肯定可以，不过可能得改改

**Comment by rodingbaba** [comment]
这个需求还是挺多的，因为大部分v4的直播源都失效了。期待大佬可以支持。感谢！

**Comment by rodingbaba** [comment]
你的捐赠图片是挂了吗？请你喝杯咖啡

**Comment by hunshcn** [comment]
不用了，不是本项目的范围，不会在这里支持。而且如果只是你描述的需求，用 cloudflare cdn 加速这个 ip 就行了。
如果说有特别多ip，需要反代的话，不需要黑名单，用 nginx 做一个反代就行，可以写个简单的供你参考（我没测试啊，但是应该差不多）

```nginx.conf
    server {
        merge_slashes off;
        listen 80;
        server_name _;
        location ~ ^/(https?)://([^/]+)/ {
            set $realscheme $1;
            set $realhost $2;
            rewrite ^/(https?://[^/]+)/(.*) /$2 break;
            proxy_pass $realscheme://$realhost;
            proxy_set_header Host $realhost;
            proxy_set_header X-Forwarded-Host $realhost;
            proxy_set_header X-Forwarded-Proto $realscheme;
            proxy_set_header X-Path-Style true;
            proxy_redirect ~^(https?://[^/]+) /$1;
            proxy_redirect / /$realstring/;
        }
    }
```

**Comment by hunshcn** [comment]
但是不加黑/白名单还是很危险的，只建议内网这么用

**Comment by hunshcn** [comment]
单纯说技术方案，还建议可以用 http_proxy 的方法，这样比较无感，虽然不知道电视设备支不支持

**Comment by rodingbaba** [comment]
http_proxy 就是电视不支持，我有搭了代理，电脑上通过http_proxy,ipv6的分流走节点是成功了。 上面那个nginx 反代可能还有个问题，就是[2409:8087:1e03:21::2]:6060  这个地址还一定是真是的地址，会跳转，我之前试了nginx反代，就是因为跳转导致不成功

**Comment by hunshcn** [comment]
连接wifi 的时候没有 代理选项吗

**Comment by rodingbaba** [comment]
是电视盒子，用的网线。是不是买usb   wifi网卡成本最低了。

**Comment by hunshcn** [comment]
网线一般的系统也有设置，买网卡倒也不至于。
如果没有确实就只能像你在1楼说的方式了。不过 m3u8 直播我不太懂没接触过，如果是 m3u8 视频，里面切片地址其实关键字也得替换，确实不是单纯的反代

**Comment by rodingbaba** [comment]
好的，那我也不考虑这种方式了，其实还是http_proxy最简单。感谢了。

**Comment by hunshcn** [comment]
看了下你发的这个源，都是相对路径的切片，反代是可行。如果绝对路径就得进行一些替换了。反代只需要注意需要处理重定向即可。我发的 nginx conf 里面有这方面的处理。

**Comment by rodingbaba** [comment]
我一会尝试一下。是不是直接粘贴你的配置，然后用http://22.1.1.1/http://[2409:8087:1e03:21::2]:6060/cms001/ch00000090990000001022/index.m3u8  这样访问。

**Comment by hunshcn** [comment]
是的

**Comment by rodingbaba** [comment]
![image](https://github.com/hunshcn/gh-proxy/assets/105403232/065918b9-59aa-413e-9521-ae9ffa729de6)
报错了

**Comment by hunshcn** [comment]
@rodingbaba 
```nginx.conf
    server {
        merge_slashes off;
        listen 8111;
        server_name _;
        location ~ ^/(https?)://([^/]+)/ {
            set $realscheme $1;
            set $realhost $2;
            rewrite ^/(https?://[^/]+)/(.*) /$2 break;
            proxy_pass $realscheme://$realhost;
            proxy_set_header Host $realhost;
            proxy_set_header X-Forwarded-Host $realhost;
            proxy_set_header X-Forwarded-Proto $realscheme;
            proxy_set_header X-Path-Style true;
            proxy_redirect ~^(https?://.+) /$1;
        }
    }
```

**Comment by rodingbaba** [comment]
@hunshcn 代理成功了！！大佬真是太强了！！十分感谢！！

**Comment by rodingbaba** [comment]
大佬，这个有没有可能部署在cf-worker上，不用消耗自己服务器的流量

**Comment by hunshcn** [comment]
可以肯定可以，改下就行

**Comment by rodingbaba** [comment]
> @rodingbaba
> 
> ```
>     server {
>         merge_slashes off;
>         listen 80;
>         server_name _;
>         location ~ ^/(https?)://([^/]+)/ {
>             set $realscheme $1;
>             set $realhost $2;
>             rewrite ^/(https?://[^/]+)/(.*) /$2 break;
>             proxy_pass $realscheme://$realhost;
>             proxy_set_header Host $realhost;
>             proxy_set_header X-Forwarded-Host $realhost;
>             proxy_set_header X-Forwarded-Proto $realscheme;
>             proxy_set_header X-Path-Style true;
>             proxy_redirect ~^(https?://.+) /$1;
>         }
>     }
> ```

@hunshcn 大佬，现在这种是域名的ipv6源 https://iptv.hiper25.com/TVB/video.m3u8  用这个nginx配置转发不了呢，这个有可能支持吗

**Comment by hunshcn** [comment]
> > @rodingbaba
> > ```
> >     server {
> >         merge_slashes off;
> >         listen 80;
> >         server_name _;
> >         location ~ ^/(https?)://([^/]+)/ {
> >             set $realscheme $1;
> >             set $realhost $2;
> >             rewrite ^/(https?://[^/]+)/(.*) /$2 break;
> >             proxy_pass $realscheme://$realhost;
> >             proxy_set_header Host $realhost;
> >             proxy_set_header X-Forwarded-Host $realhost;
> >             proxy_set_header X-Forwarded-Proto $realscheme;
> >             proxy_set_header X-Path-Style true;
> >             proxy_redirect ~^(https?://.+) /$1;
> >         }
> >     }
> > ```
> 
> @hunshcn 大佬，现在这种是域名的ipv6源 https://iptv.hiper25.com/TVB/video.m3u8 用这个nginx配置转发不了呢，这个有可能支持吗

这个配置没有对 ipv6 有限制，但也没做特殊处理。我不清楚是什么情况，如果不能使用
1. 确保实例有 ipv6 访问能力
2. 可以贴 error log 帮你看看

**Comment by rodingbaba** [comment]
感谢！我之前都没想起来去看nginx日志。no resolver defined to resolve  是报这个错，我加了一行resolver 8.8.8.8;  解决了。
