### ISSUE TITLE
为什么有些链接会502？

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [hunshcn/gh-proxy#117]
https://mirror.ghproxy.com/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat
https://ghproxy.org/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat

https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat是可以正常访问的

**Comment by hunshcn** [comment]
镜像站可能会对一些异常地址进行屏蔽，这很正常。有可能是内容异常，也有可能是有异常客户端高频请求。

不要再来问镜像站的事情了。这就是早期一直没有开贴搜集的部分原因，非我可控。

**Comment by libsgh** [comment]
> 镜像站可能会对一些异常地址进行屏蔽，这很正常。有可能是内容异常，也有可能是有异常客户端高频请求。
> 
> 不要再来问镜像站的事情了。这就是早期一直没有开贴搜集的部分原因，非我可控。

我自己的站发现也下载不了这个文件，看了下日志是nginx报错
`upstream sent too big header while reading response header from upstream`，由于镜像用了uwsgi，所以稍微改了一下配置并提了个[pr](https://github.com/hunshcn/gh-proxy/pull/118)。以下是测试地址：https://gh.noki.eu.org/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat

**Comment by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [comment]
> > 镜像站可能会对一些异常地址进行屏蔽，这很正常。有可能是内容异常，也有可能是有异常客户端高频请求。
> > 不要再来问镜像站的事情了。这就是早期一直没有开贴搜集的部分原因，非我可控。
> 
> 我自己的站发现也下载不了这个文件，看了下日志是nginx报错 `upstream sent too big header while reading response header from upstream`，由于镜像用了uwsgi，所以稍微改了一下配置并提了个[pr](https://github.com/hunshcn/gh-proxy/pull/118)。以下是测试地址：https://gh.noki.eu.org/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat

我也测试了，uwsgi部署的都下载不了，用gunicorn部署能少很多问题，建议用gunicorn

**Comment by libsgh** [comment]
> > > 镜像站可能会对一些异常地址进行屏蔽，这很正常。有可能是内容异常，也有可能是有异常客户端高频请求。
> > > 不要再来问镜像站的事情了。这就是早期一直没有开贴搜集的部分原因，非我可控。
> > 
> > 
> > 我自己的站发现也下载不了这个文件，看了下日志是nginx报错 `upstream sent too big header while reading response header from upstream`，由于镜像用了uwsgi，所以稍微改了一下配置并提了个[pr](https://github.com/hunshcn/gh-proxy/pull/118)。以下是测试地址：https://gh.noki.eu.org/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat
> 
> 我也测试了，uwsgi部署的都下载不了，用gunicorn部署能少很多问题，建议用gunicorn
更新下吧，设置下buffer已经可以了

**Comment by stilleshan** [comment]
releases/latest/download
自动跳转逻辑貌似 github 这边变了。
打包昨天更新的镜像重新部署，貌似还是502错误

一些网友说之前用releases/latest/download一直没问题，就是最近几天出现的问题

**Comment by stilleshan** [comment]
https://github.com/hacs/integration/releases/latest/download/hacs.zip
例如这个拉取最新版就报错502

指定tag就没问题
https://github.com/hacs/integration/releases/download/1.34.0/hacs.zip

**Comment by libsgh** [comment]
> releases/latest/download 自动跳转逻辑貌似 github 这边变了。 打包昨天更新的镜像重新部署，貌似还是502错误
> 
> 一些网友说之前用releases/latest/download一直没问题，就是最近几天出现的问题

如果说是报nginx 502那就更新一下，猜测是releases/latest/download的响应头发生了变化，超出了缓冲区的默认大小。我这边测试你发的链接都是可以下载的。

**Comment by stilleshan** [comment]
用你的站点可以，但是mirror.ghproxy.com 还是不行，不过我的 dockerfile 的 From 不一样，我改回来试试看

**Comment by libsgh** [comment]
> 用你的站点可以，但是mirror.ghproxy.com 还是不行，不过我的 dockerfile 的 From 不一样，我改回来试试看

需要根据你的部署环境，如果是nginx+uwsgi，才设置uwsgi_buffer，如果是nginx+proxy 需要设置proxy_buffer，如果是nginx+php设置fastcgi_buffer

**Comment by libsgh** [comment]
> > 用你的站点可以，但是mirror.ghproxy.com 还是不行，不过我的 dockerfile 的 From 不一样，我改回来试试看
> 
> 需要根据你的部署环境，如果是nginx+uwsgi，才设置uwsgi_buffer，如果是nginx+proxy 需要设置proxy_buffer，如果是nginx+php设置fastcgi_buffer

所以，worker版本没这个问题

**Comment by stilleshan** [comment]
已解决，反代的配置没改。改了就好了

**Comment by 0-RTT** [comment]
> > 用你的站点可以，但是mirror.ghproxy.com 还是不行，不过我的 dockerfile 的 From 不一样，我改回来试试看
> 
> 需要根据你的部署环境，如果是nginx+uwsgi，才设置uwsgi_buffer，如果是nginx+proxy 需要设置proxy_buffer，如果是nginx+php设置fastcgi_buffer 所以，worker版本没这个问题

你好，我使用的nginx反代，clone提示The requested URL returned error: 502，请问要怎么修改配置？
```
location / {
    proxy_pass http://127.0.0.1:1234/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_set_header Connection '';
}
``

**Comment by hunshcn** [comment]
> > > 用你的站点可以，但是mirror.ghproxy.com 还是不行，不过我的 dockerfile 的 From 不一样，我改回来试试看
> > 
> > 
> > 需要根据你的部署环境，如果是nginx+uwsgi，才设置uwsgi_buffer，如果是nginx+proxy 需要设置proxy_buffer，如果是nginx+php设置fastcgi_buffer 所以，worker版本没这个问题
> 
> 你好，我使用的nginx反代，clone提示The requested URL returned error: 502，请问要怎么修改配置？
> 
> ```
> location / {
>     proxy_pass http://127.0.0.1:1234/;
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header Range $http_range;
>     proxy_set_header If-Range $http_if_range;
>     proxy_set_header Connection '';
> }
> ``
> ```

https://github.com/hunshcn/gh-proxy/pull/118/files
看这里

**Comment by hunshcn** [comment]
close with #118

**Comment by 0-RTT** [comment]
> > > > 用你的站点可以，但是mirror.ghproxy.com 还是不行，不过我的 dockerfile 的 From 不一样，我改回来试试看
> > > 
> > > 
> > > 需要根据你的部署环境，如果是nginx+uwsgi，才设置uwsgi_buffer，如果是nginx+proxy 需要设置proxy_buffer，如果是nginx+php设置fastcgi_buffer 所以，worker版本没这个问题
> > 
> > 
> > 你好，我使用的nginx反代，clone提示The requested URL returned error: 502，请问要怎么修改配置？
> > ```
> > location / {
> >     proxy_pass http://127.0.0.1:1234/;
> >     proxy_set_header Host $host;
> >     proxy_set_header X-Real-IP $remote_addr;
> >     proxy_set_header Range $http_range;
> >     proxy_set_header If-Range $http_if_range;
> >     proxy_set_header Connection '';
> > }
> > ``
> > ```
> 
> https://github.com/hunshcn/gh-proxy/pull/118/files 看这里

可以用nginx反代吗？下面是gpt给的配置，还是提示502。
```
location / {
    proxy_pass http://127.0.0.1:59740/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_set_header Connection '';

    proxy_buffer_size   256k;
    proxy_buffers       4 512k;
    proxy_busy_buffers_size 512k;
    proxy_temp_file_write_size 512k; 
}

```

**Comment by hunshcn** [comment]
@0-RTT 

我没看出来有问题，` nginx -s reload` 重新加载配置，如果还是不行可以看下 nginx log

**Comment by 0-RTT** [comment]
> nginx -s reload

2024/03/10 23:38:12 [error] 58753#0: *19 upstream sent duplicate header line: "Transfer-Encoding: chunked", previous value: "Transfer-Encoding: chunked" while reading response header from upstream, client: 120.231.213.121, server: , request: "GET /https://github.com/6dylan6/jdpro.git/info/refs?service=git-upload-pack HTTP/2.0", upstream: "http://127.0.0.1:1234/https:/github.com/6dylan6/jdpro.git/info/refs?service=git-upload-pack", host: ""

**Comment by hunshcn** [comment]
> > nginx -s reload
> 
> 2024/03/10 23:38:12 [error] 58753#0: *19 upstream sent duplicate header line: "Transfer-Encoding: chunked", previous value: "Transfer-Encoding: chunked" while reading response header from upstream, client: 120.231.213.121, server: , request: "GET /https://github.com/6dylan6/jdpro.git/info/refs?service=git-upload-pack HTTP/2.0", upstream: "http://127.0.0.1:1234/https:/github.com/6dylan6/jdpro.git/info/refs?service=git-upload-pack", host: ""

这与上面讨论的内容不太一样，我明天看看吧
