### ISSUE TITLE
基于Golang的gh-proxy版本

### ISSUE THREAD

**Issue by iuu6** [hunshcn/gh-proxy#119]
根据贵方MIT协议，我们重新开发了**Golang语言**版本
https://github.com/iuu6/gh-proxy
这是我们的链接，采用GPL协议，并没有违反MIT协议的有关内容，如果有侵犯贵方的利益或其他，请直接提出，谢谢！

**Comment by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [comment]
性能会不会更强？

**Comment by iuu6** [comment]
> 性能会不会更强？

理论来说是的？Go语言高并发能力更强，但是这个程序**没有经过严格测试**，可能存在**未知bug**
https://www.ten-year.link/
我也部署了一个用来测试和使用，但是不保证稳定（速度不一定快，因为就是套了个cloudflare）您可以测试使用

**Comment by libsgh** [comment]
重复的轮子，没什么必要吧....

**Comment by iuu6** [comment]
> 重复的轮子，没什么必要吧....

大概或许确实是这样，但是一些小硬盘大流量的服务器就可以利用Go语言高性能和不需要运行环境的优势快速部署
