### ISSUE TITLE
can not accelerate https://github.com/VoronDesign/Voron-2/raw/Voron2.4/Docs/2.4_Assembly_Manual.pdf

### ISSUE THREAD

**Issue by QGB** [hunshcn/gh-proxy#12]
`https://github.com/VoronDesign/Voron-2/raw/Voron2.4/Docs/2.4_Assembly_Manual.pdf`

**Comment by hunshcn** [comment]
use https://github.com/VoronDesign/Voron-2/blob/Voron2.4/Docs/2.4_Assembly_Manual.pdf

**Comment by QGB** [comment]
@hunshcn add auto trans
