### ISSUE TITLE
部署后直接522？

### ISSUE THREAD

**Issue by potus2030** [hunshcn/gh-proxy#122]
实际上测试页面就是直接522

**Comment by hunshcn** [comment]
请提供具体信息

**Comment by potus2030** [comment]
> 请提供具体信息

找到问题所在了。是本人理解错误，ASSET 那个URL，我前面填成了自己worker里面的域名URL了。其实应该填本项目地址就可以了。

**Comment by gimgoo** [comment]
I accessed it after deploying it via cloudflare worker and it also says 522 without any further information, just "error code: 522".

The worker route is: abc.example.com/*
ASSET_URL is: https://abc.example.com/
PREFIX is: /

What's wrong with this?
