### ISSUE TITLE
二级域名也没了吗

### ISSUE THREAD

**Issue by hncaiyin** [hunshcn/gh-proxy#128]
没了吗？用梯子一开始可以上，没多久就没了，一级域名用梯子可以上。

**Comment by hunshcn** [comment]
？

**Comment by hncaiyin** [comment]
![IMG_20240511_212501](https://github.com/hunshcn/gh-proxy/assets/64884813/188fb356-7ca0-4e7f-8ec4-1e8c23aa6b33)
广东电信打不开，要科学上网了

**Comment by hncaiyin** [comment]
> ![IMG_20240511_212501](https://private-user-images.githubusercontent.com/64884813/329824057-188fb356-7ca0-4e7f-8ec4-1e8c23aa6b33.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDY4OTksIm5iZiI6MTcxNTUwNjU5OSwicGF0aCI6Ii82NDg4NDgxMy8zMjk4MjQwNTctMTg4ZmIzNTYtN2NhMC00ZTdmLThlYzQtMWU4YzIzYWE2YjMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA5MzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNGQxNzNiODQ4MDZjNzU3M2M1MjViZmY0ZGJhMDFiMGU0OGM5YjJjMTE0NGYxNTY0MmQyYzg3N2QyMGE2ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p7zGd1fYpFUOJeVBu3EAX1PVXv1NZlFPP00e2vmNSYQ) 广东电信打不开，要科学上网了



> ![IMG_20240511_212501](https://private-user-images.githubusercontent.com/64884813/329824057-188fb356-7ca0-4e7f-8ec4-1e8c23aa6b33.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDcwNzgsIm5iZiI6MTcxNTUwNjc3OCwicGF0aCI6Ii82NDg4NDgxMy8zMjk4MjQwNTctMTg4ZmIzNTYtN2NhMC00ZTdmLThlYzQtMWU4YzIzYWE2YjMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA5MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OWNiYTgwMDUwMzM2MjRkNWQ3Njg3MjQ5N2M4NDBiMThiYjc0MDkxMzY4MjU2Yjg0MmY0NjBiNTcxZTVmYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JxnZ46vltpr5nlNd5k-3xfIAvzieUIxU0wY1S2bzJwA) 广东电信打不开，要科学上网了

换了dns，解决了。
