### ISSUE TITLE
提供 GitHub API 支持

### ISSUE THREAD

**Issue by zzc-tongji** [hunshcn/gh-proxy#133]
能否提供对 [GitHub API](https://api.github.com/) 的支持？

包括对 GET / POST / UPDATE / DELETE 请求和响应的转发。

例如 **https://GH_PROXY.EXAMPLE_SITE/** http://api.github.com/repo/OWNER/REPO 。

**Comment by hunshcn** [comment]
感谢你的贡献，在之前的诸多 issue 都有人希望此能力。但是这超出了这个 repo 希望覆盖的范围。

尤其对于自建需求，建议使用 https://github.com/kubernetes-sigs/prow/blob/main/site/content/en/docs/ghproxy/_index.md

普通的 proxy 并不能提供良好的体验。

**Comment by dishao123** [comment]
强烈希望作者合并

**Comment by zzc-tongji** [comment]
好吧。我自己有这个需求而且急用，所以就 fork 自己改了。@dishao123 你可以用我的版本。

https://github.com/zzc-tongji/gh-proxy/tree/master-owner
https://hub.docker.com/r/zzcgwu/gh-proxy

**Comment by dishao123** [comment]
> 好吧。我自己有这个需求而且急用，所以就 fork 自己改了。@dishao123 你可以用我的版本。
> 
> https://github.com/zzc-tongji/gh-proxy/tree/master-owner https://hub.docker.com/r/zzcgwu/gh-proxy

支持 worker 部署吗?

**Comment by zzc-tongji** [comment]
> > 好吧。我自己有这个需求而且急用，所以就 fork 自己改了。@dishao123 你可以用我的版本。
> 
> > 
> 
> > https://github.com/zzc-tongji/gh-proxy/tree/master-owner https://hub.docker.com/r/zzcgwu/gh-proxy
> 
> 
> 
> 支持 worker 部署吗?

现在支持了。

**Comment by dishao123** [comment]
> > > 好吧。我自己有这个需求而且急用，所以就 fork 自己改了。@dishao123 你可以用我的版本。
> > 
> > 
> > > 
> > 
> > 
> > > https://github.com/zzc-tongji/gh-proxy/tree/master-owner https://hub.docker.com/r/zzcgwu/gh-proxy
> > 
> > 
> > 支持 worker 部署吗?
> 
> 现在支持了。

感谢

**Comment by dishao123** [comment]
@zzc-tongji 请教一下大佬，我想加速 ghcr.io 应该怎么做？

**Comment by dishao123** [comment]
@zzc-tongji 大佬，我使用你仓库中的 worker 版本部署后访问 https://gh.xv.gs/https://api.github.com/users/dishao123 出现 404 怎么办？

**Comment by zzc-tongji** [comment]
我自己用的是 docker 版本，CF 版本未测试。

**Comment by dishao123** [comment]
> 我自己用的是 docker 版本，CF 版本未测试。

我也不会
