### ISSUE TITLE
右上角的Fork me on Github变反色了

### ISSUE THREAD

**Issue by BoyceLig** [hunshcn/gh-proxy#14]
![image](https://user-images.githubusercontent.com/49801599/86423755-2c17b180-bd13-11ea-8fd4-9445f63507f2.png)

**Comment by hunshcn** [comment]
https://github.com/hunshcn/hunshcn.github.io/commit/f55c9fa85f2adadbb85b9e067f958c1329c3d6e9 修复了，一个小失误贴错图片地址了...

**Comment by Chandler-Lu** [comment]
2333早上乍一眼还以为我暗黑模式出bug了。。
