### ISSUE TITLE
能否添加CF Pages的支持

### ISSUE THREAD

**Issue by shulng** [hunshcn/gh-proxy#140]

**Comment by hunshcn** [comment]
如果有不能使用 worker 但是 page 可以的原因，那么将愿意接受贡献

**Comment by yangyanggu** [comment]
https://github.com/yangyanggu/gh-proxy-page   试试

**Comment by shulng** [comment]
> https://github.com/yangyanggu/gh-proxy-page 试试

好的谢谢
