### ISSUE TITLE
Git clone 大容量仓库出错。

### ISSUE THREAD

**Issue by stilleshan** [hunshcn/gh-proxy#143]
由于需求需要 git clone 一些包含全部 commit 的大容量仓库，一般在 1-5 G 不等，总是在 clone 中间断掉，已经尝试排查，甚至不用 nginx 反代，直接 clone http://127.0.0.1:8080/https://github.com/xxx/xxx 都会频繁有这种问题。

```
Cloning into 'linux-rockchip'...
remote: Enumerating objects: 10113557, done.
remote: Counting objects: 100% (2271/2271), done.
remote: Compressing objects: 100% (500/500), done.
fatal: the remote end hung up unexpectedly, 1.07 GiB | 49.16 MiB/s      
fatal: early EOF
fatal: index-pack failed
```

请问是否在 main.py 的 flask 有所优化能够解决？

这里有个示例仓库我一直无法代理 clone
https://github.com/armbian/linux-rockchip

**Comment by hunshcn** [comment]
未复现，换个机器呢
```bash
docker run -d --rm --name="gh-proxy-py" -p 0.0.0.0:8888:80 hunsh/gh-proxy-py:latest
```
<img width="704" alt="image" src="https://github.com/user-attachments/assets/6024ffb3-ca5d-412d-b734-bc1cd7dce078">

**Comment by stilleshan** [comment]
换了服务器测试要好些了，目前程序没问题，但是前面做了nginx反向代理，其他电脑用域名访问，就大概率出现这个问题。
