### ISSUE TITLE
能否整合 glare 项目的功能

### ISSUE THREAD

**Issue by loveqianool** [hunshcn/gh-proxy#15]
项目地址 https://github.com/Contextualist/glare

想要使用 https://gh.api.99988866.xyz/xtaci/kcptun/kcptun-windows-amd64 下载最新版本的 kcptun

**Comment by hunshcn** [comment]
如果有同样需求的底下附一下吧，如果需求不大就先不做了，最近比较懒 (￣∠￣)ﾉ

**Comment by zbwxtex** [comment]
有(我不需要反正功能越多越好因为不用我的硬盘(bushi

**Comment by loveqianool** [comment]
> 有(我不需要反正功能越多越好因为不用我的硬盘(bushi

已经有了。

[https://www.hostloc.com/forum.php?mod=redirect&goto=findpost&ptid=712691&pid=8744169](url)
