### ISSUE TITLE
演示站图片问题

### ISSUE THREAD

**Issue by Kawaii-KM** [hunshcn/gh-proxy#16]
![屏幕快照 2020-07-08 21 25 33](https://user-images.githubusercontent.com/56059155/86924644-537edc00-c162-11ea-8b2b-c44214c57eba.png)
（通过 Cloudflare Workers 部署时发现

**Comment by hunshcn** [comment]
啊这...用腾讯的图床看来是触发防盗链了
...我这边没问题，不过现在改了referrerPolicy，应该不会再触发防盗链了

**Comment by Kawaii-KM** [comment]
可以试试[这个](https://github.com/tholman/github-corners)

**Comment by hunshcn** [comment]
哈哈这个不是特别重要，能正常就好了
