### ISSUE TITLE
能否加一下raw之类的链接分解

### ISSUE THREAD

**Issue by eicky** [hunshcn/gh-proxy#18]
因为很多脚本都是直接指向了raw(eg:`https://raw.githubusercontent.com/hiCasper/Shell/master/AutoReinstall.sh`)，所以每次都需要先找到原文件复制成`https://github.com/hiCasper/Shell/blob/master/AutoReinstall.sh`这种链接才可以使用，有一点麻烦，希望可以增加一下

**Comment by eicky** [comment]
看到你写的`2020.04.10 增加对raw.githubusercontent.com文件的支持`
但是我用你的demo链接测试，提示`请与所请求的格式保持一致`

**Comment by eicky** [comment]
找到问题了，是前端的提示问题，直接链接前面加上是可以用的

**Comment by hunshcn** [comment]
😅是哦前端没改，明天加上，感谢指出

**Comment by hunshcn** [comment]
https://github.com/hunshcn/hunshcn.github.io/commit/d8c53ca8eca3a7e90aa7b99367258235ed5775fe
