### ISSUE TITLE
关于子目录的报错问题

### ISSUE THREAD

**Issue by GiriNeko** [hunshcn/gh-proxy#2]
我的环境是Cloudflare Workers.
使用Workers自己的域名，是可以正常访问的。
但是在Clouflare域名设置中开启Workers路由功能后，路由过的域名（也就是api.ineko.cc)就会报`error code: 1000`的错误。
![image](https://user-images.githubusercontent.com/21117880/79643730-e7ca4a00-81d6-11ea-9fef-cb10e3ab7327.png)
![image](https://user-images.githubusercontent.com/21117880/79643757-04ff1880-81d7-11ea-9068-2aa5608456d6.png)
我尝试修改了js文件无果。
求解..

**Comment by hunshcn** [comment]
之前确实不支持子目录，刚改了一下，已经支持，修改PREFIX变量为/gh-proxy/即可（注意有两个斜杠），还有你的ASSET_URL是错误的，这样访问/gh-proxy/会导致回环，无限访问自己，可以参考一下更新的readme

**Comment by GiriNeko** [comment]
已解决，谢谢！
