### ISSUE TITLE
docker 版的问题还是vps问题?

### ISSUE THREAD

**Issue by stilleshan** [hunshcn/gh-proxy#20]
你的最新源码和dockerfile做了镜像.并启动
jsdelivr = 0
cnpmjs = 0
时 git clone 总提示500错误.
而且直接页面下载经常失败,要刷新几次才行.

后来改为
jsdelivr = 1
cnpmjs = 1
新版的raw.githubusercontent.com支持也报错...

不知道时我vps问题还是镜像问题..求解.

**Comment by hunshcn** [comment]
修复 https://github.com/hunshcn/gh-proxy/commit/23b9fa312e3e0a7920e101b48050e3d6b4c5bc98
其实挺奇怪的我记得测试过没问题的...

**Comment by stilleshan** [comment]
测试了下改为0走本机貌似好了..没有过多测试.
但是raw地址还是无法下载,无论是web端 还是 wget

server error Invalid URL 'https:/raw.githubusercontent.com/stilleshan/gh-proxy/master/Dockerfile': No host supplied

**Comment by hunshcn** [comment]
找到问题了，因为我测试是直接run，但是docker版被nginx反代之后会缺失一个"/"，已经在代码里加上判断了

**Comment by stilleshan** [comment]
现在 wget raw 没问题了.不过web端还是下载不了,我估计是反向代理nginx没配置文件类型.不知道是否有安全隐患 能请教一下吗?

**Comment by hunshcn** [comment]
web端下载不了是什么情况呢，意思是直接在浏览器显示吗

**Comment by stilleshan** [comment]
https://g.ioiox.com
直接在文本框里粘贴 https://raw.githubusercontent.com/hunshcn/gh-proxy/master/Dockerfile 点下载还是无法下,在你的演示站就可以

目前在终端里 wget https://g.ioiox.com/https://raw.githubusercontent.com/hunshcn/gh-proxy/master/Dockerfile 是没有问题

**Comment by stilleshan** [comment]
新版本已解决
