### ISSUE TITLE
加速的原理是什么？

### ISSUE THREAD

**Issue by nelhu** [hunshcn/gh-proxy#23]
如题

**Comment by hunshcn** [comment]
其实就是一个反向代理而已，不过指定了源站并且做了整合

**Comment by nelhu** [comment]
> 其实就是一个反向代理而已，不过指定了源站并且做了整合

没太懂，是反向代理到了加速通道？还是源站？

**Comment by hunshcn** [comment]
User -> Cloudflare/your server -> github server
如果开启了jsdelivr或者cnpmjs选项，并且击中规则，这个中间服务器会变成jsdelivr/cnpmjs

**Comment by nelhu** [comment]
> User -> Cloudflare/your server -> github server
> 
> 如果开启了jsdelivr或者cnpmjs选项，并且击中规则，这个中间服务器会变成jsdelivr/cnpmjs

醍醐灌顶😯
