### ISSUE TITLE
[建议]add gist

### ISSUE THREAD

**Issue by zut** [hunshcn/gh-proxy#24]
建议支持: https://gist.github.com/

**Comment by cielpy** [comment]
经测试，是支持的，比如

https://gh-proxy.imciel.com/https://gist.github.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/2419d6e9c63996840e7e8e4a571c57086fa959c3/cmd.py

**Comment by huLter** [comment]
https://gist.githubusercontent.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/cmd.py
但是这类地址就不支持了

**Comment by cielpy** [comment]
> https://gist.githubusercontent.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/cmd.py
> 但是这类地址就不支持了

@huLter 是的，暂时可以通过用 gist.github.com 域名的地址来使用

**Comment by cielpy** [comment]
> https://gist.githubusercontent.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/cmd.py
> 但是这类地址就不支持了

刚才点击了一下，是可以打开的

**Comment by hunshcn** [comment]
没有邮件给我轰炸一下我完全没想起来

已经加上了

**Comment by cielpy** [comment]
这种情况少处理了 https://gist.github.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/2419d6e9c63996840e7e8e4a571c57086fa959c3/cmd.py

**Comment by hunshcn** [comment]
> 这种情况少处理了 https://gist.github.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/2419d6e9c63996840e7e8e4a571c57086fa959c3/cmd.py

ok，已经加上
