### ISSUE TITLE
问下 Cloudflare Workers 是否可以指定自选 CDN IP？

### ISSUE THREAD

**Issue by XIU2** [hunshcn/gh-proxy#25]
搭建 Python 版本毕竟还需要消耗服务器流量，就想着用 Workers 会好点，但是我只知道可以用其他方法给搭建在服务器上的网站指定自选 Cloudflare CDN IP，但是不知道 Workers 是否也能这样做。

特来问一下，这样正好可以用我写的 [Cloudflare CDN 测速工具](https://github.com/XIU2/CloudflareSpeedTest) 来获得最快 IP~  

> Cloudflare 默认分配的给中国访客的 IP 比较差，如果可以自选 CDN IP 会好很多。

**Comment by hunshcn** [comment]
理论上是可以的，不过之前有出现走指定ip证书错误的情况。这个项目本来也不是针对个人使用的情况做的，因为个人使用有更多更方便的方法，比如搭建sni proxy，或者nginx反代。面向大众的服务自选ip意义不大，有需要自行测试吧。

**Comment by XIU2** [comment]
我不是个人用的，我是想自己搭建一个给别人用，但是又担心成本问题。。。  

想放到我这个油猴脚本中给别人使用：[Github 增强 - 高速下载](https://greasyfork.org/zh-CN/scripts/412245) 
> 目前脚本内的加速下载网站都是别人提供的，我想要自己也搞个，同时要搞就要个好点的。

另外，你看看这个网站：https://gh.con.sh 用的是你的项目吗？这个域名就只指向了 `104.17.1.1/104.17.0.1` 。

**Comment by XIU2** [comment]
另外，其中一个加速下载网站似乎是因为用的人太多，导致 IP 被 Github 加入黑名单了？
无论加速什么链接，Github 都会提示：
```
Whoa there!
You have sent an invalid request.

Please do not send this request again.
```
你看看：https://git.yumenaka.net/https://github.com/XIU2/CloudflareSpeedTest/archive/v1.4.6.zip

**Comment by hunshcn** [comment]
没有更多的人报告这个情况，所以我不认为这个是反爬虫机制，或许他可能出现了一些意外，可以在这台服务器上执行
```
curl https://github.com/XIU2/CloudflareSpeedTest/archive/v1.4.6.zip
```
尝试能否复现

**Comment by XIU2** [comment]
emmm 主要是我现在联系不到这个网站的站长，这个人好像自己也没发现这个问题，这就很尴尬了。。。  
这个问题我只是顺便问下，等我联系到这个网站的站长后，在讨论这个问题吧。。。

似乎跑题了，“不过之前有出现走指定ip证书错误的情况”你以前尝试过指定自选 IP 吗？
指定方式和正常网站指定自选 IP 是一样的方法吗？（去那些网站 CANME 接入域名？）

**Comment by hunshcn** [comment]
很早之前的尝试了，因为那时候图简单cname v2ex.com，然后出现证书错误。可以自己尝试

**Comment by XIU2** [comment]
哈！我成功了。  

一开始我都不知道怎么自定义域名，网上查了下也没人说怎么自选 IP，但是我研究了下发现可以：

正常部署完 Workers 后，去添加一个子域名记录（不开启代理）指向自选 IP，然后再去域名的 Workers 中添加路由指向一开始时部署的 Workers 服务就行了。

> 重点是，添加子域名记录时**不能开启代理（橙色的 ☁）**，否则就不会指向自选 IP 了。

**Comment by XIU2** [comment]
奇怪，我明明关闭了分支文件使用 jsDelivr 镜像的开关：
```
const Config = {
    jsdelivr: 0,
    cnpmjs: 1
}
```

为什么访问还是会重定向到 jsDelivr 呢...

**Comment by XIU2** [comment]
对了，好奇问一下，你提供的演示网站用的 Workers 每天免费的 10 万次够用吗？  
我不清楚使用量如何，担心 10万次不够用了怎么办，毕竟我是为了无成本才选择的 Workers。。。

**Comment by hunshcn** [comment]
> 对了，好奇问一下，你提供的演示网站用的 Workers 每天免费的 10 万次够用吗？
> 我不清楚使用量如何，担心 10万次不够用了怎么办，毕竟我是为了无成本才选择的 Workers。。。

可以自己修改代码然后使用多个workers分流，但是不需要担心，我的演示站现在都没超

**Comment by hunshcn** [comment]
> 奇怪，我明明关闭了分支文件使用 jsDelivr 镜像的开关：
> 
> ```
> const Config = {
>     jsdelivr: 0,
>     cnpmjs: 1
> }
> ```
> 
> 为什么访问还是会重定向到 jsDelivr 呢...

请提供输入参数以复现

**Comment by XIU2** [comment]
刚才试了下又正常了。。。  
当初我测试的时候，是照着一个 URL 测试的，可能一开始还没关掉或还没生效？后来改了之后同一个文件又有缓存？

总之现在正常了。
