### ISSUE TITLE
能不能做成一个 https proxy

### ISSUE THREAD

**Issue by norci** [hunshcn/gh-proxy#28]
就是按这方法设置成代理：

`git config --global https.proxy https://ghproxy.com`

好像 https proxy 不能看到 URI ？

**Comment by zwc456baby** [comment]
```
git config --global url."https://pd.zwc365.com/seturl/https://github.com/".insteadOf https://github.com/
```

上面这里是一个示例代理，修改一下就可以实现你所说的 https proxy 了。例如修改成这样：

```
git config --global url."https://gh.api.99988866.xyz/https://github.com/".insteadOf https://github.com/
```

执行上面这样的配置后，所有 github.com 的项目，都会走代理 `gh.api.99988866.xyz`

**Comment by norci** [comment]
it works.
Many thanks!
