### ISSUE TITLE
新版VPS的docker部署全部 HTTP ERROR 400

### ISSUE THREAD

**Issue by stilleshan** [hunshcn/gh-proxy#29]
如题.

VPS docker部署,任何链接都报 400 错误.

**Comment by hunshcn** [comment]
没有发现这个问题
http://47.245.11.21/https://gist.github.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/2419d6e9c63996840e7e8e4a571c57086fa959c3/cmd.py

**Comment by stilleshan** [comment]
奇怪了.
我拿一台新服务器,什么都没装,直接启动你的容器.除了glist可以,其他都不行(后来又换了一台服务器也是一样)
http://140.238.4.243/

我试了你上面的服务器缺没问题.

下面是相关日志.


Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Running inside /app/prestart.sh, you could add migrations to this file, e.g.:

#! /usr/bin/env bash

# Let the DB start
sleep 10;
# Run migrations
alembic upgrade head

/usr/lib/python2.7/dist-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2021-03-25 02:34:14,169 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-03-25 02:34:14,169 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2021-03-25 02:34:14,179 INFO RPC interface 'supervisor' initialized
2021-03-25 02:34:14,179 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-03-25 02:34:14,179 INFO supervisord started with pid 1
2021-03-25 02:34:15,182 INFO spawned: 'nginx' with pid 11
2021-03-25 02:34:15,183 INFO spawned: 'uwsgi' with pid 12
[uWSGI] getting INI configuration from /app/uwsgi.ini
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini

;uWSGI instance configuration
[uwsgi]
cheaper = 2
processes = 16
ini = /app/uwsgi.ini
module = main
callable = app
ini = /etc/uwsgi/uwsgi.ini
socket = /tmp/uwsgi.sock
chown-socket = nginx:nginx
chmod-socket = 664
hook-master-start = unix_signal:15 gracefully_kill_them_all
need-app = true
die-on-term = true
show-config = true
;end of configuration

*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Mar 25 02:34:15 2021] ***
compiled with version: 8.3.0 on 07 February 2021 19:39:50
os: Linux-4.14.129-bbrplus #1 SMP Tue Jun 25 12:23:41 UTC 2019
nodename: a56195e104a4
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.9 (default, Jan 12 2021, 17:26:22)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x562f9300aeb0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1239640 bytes (1210 KB) for 16 cores
*** Operational MODE: preforking ***
2021-03-25 02:34:16,225 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-25 02:34:16,226 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x562f9300aeb0 pid: 12 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12)
spawned uWSGI worker 1 (pid: 14, cores: 1)
spawned uWSGI worker 2 (pid: 15, cores: 1)
running "unix_signal:15 gracefully_kill_them_all" (master-start)...
[pid: 14|app: 0|req: 1/1] 103.116.47.52 () {38 vars in 719 bytes} [Thu Mar 25 02:34:22 2021] GET / => generated 4796 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
103.116.47.52 - - [25/Mar/2021:02:34:22 +0000] "GET / HTTP/1.1" 200 4796 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
[pid: 14|app: 0|req: 2/2] 103.116.47.52 () {38 vars in 672 bytes} [Thu Mar 25 02:34:22 2021] GET /favicon.ico => generated 3262 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
103.116.47.52 - - [25/Mar/2021:02:34:22 +0000] "GET /favicon.ico HTTP/1.1" 200 3262 "http://140.238.4.243/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
[pid: 14|app: 0|req: 3/3] 103.116.47.52 () {40 vars in 877 bytes} [Thu Mar 25 02:34:26 2021] GET /https://github.com/stilleshan/ServerStatus/archive/master.zip => generated 0 bytes in 738 msecs (HTTP/1.1 400) 1 headers in 68 bytes (0 switches on core 0)
103.116.47.52 - - [25/Mar/2021:02:34:26 +0000] "GET /https://github.com/stilleshan/ServerStatus/archive/master.zip HTTP/1.1" 400 5 "http://140.238.4.243/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
[pid: 15|app: 0|req: 1/4] 103.116.47.52 () {40 vars in 985 bytes} [Thu Mar 25 02:35:23 2021] GET /https://gist.github.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/2419d6e9c63996840e7e8e4a571c57086fa959c3/cmd.py => generated 800 bytes in 1053 msecs (HTTP/1.1 200) 23 headers in 847 bytes (1 switches on core 0)
103.116.47.52 - - [25/Mar/2021:02:35:25 +0000] "GET /https://gist.github.com/cielpy/351557e6e465c12986419ac5a4dd2568/raw/2419d6e9c63996840e7e8e4a571c57086fa959c3/cmd.py HTTP/1.1" 200 800 "http://140.238.4.243/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
[pid: 14|app: 0|req: 4/5] 103.116.47.52 () {40 vars in 905 bytes} [Thu Mar 25 02:35:37 2021] GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile => generated 14 bytes in 0 msecs (HTTP/1.1 403) 2 headers in 86 bytes (1 switches on core 0)
103.116.47.52 - - [25/Mar/2021:02:35:37 +0000] "GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile HTTP/1.1" 403 14 "http://140.238.4.243/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"

**Comment by hunshcn** [comment]
...uwsgi这边出错了，我不清楚原因，我想办法解决一下

**Comment by stilleshan** [comment]
更新了你的docker镜像后
raw 链接提示 403 错误 和 Invalid input.
http://140.238.4.243/https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile

---

[pid: 15|app: 0|req: 6/14] 103.116.47.51 () {42 vars in 928 bytes} [Sat Mar 27 14:42:04 2021] GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile => generated 14 bytes in 0 msecs (HTTP/1.1 403) 2 headers in 86 bytes (1 switches on core 0)
[pid: 14|app: 0|req: 9/15] 103.116.47.51 () {44 vars in 829 bytes} [Sat Mar 27 14:42:04 2021] GET /favicon.ico => generated 3262 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
103.116.47.51 - - [27/Mar/2021:14:42:04 +0000] "GET /favicon.ico HTTP/1.1" 200 3262 "http://140.238.4.243/https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
[pid: 14|app: 0|req: 10/16] 103.116.47.51 () {34 vars in 524 bytes} [Sat Mar 27 14:42:20 2021] GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile => generated 14 bytes in 0 msecs (HTTP/1.1 403) 2 headers in 86 bytes (1 switches on core 0)
103.116.47.51 - - [27/Mar/2021:14:42:20 +0000] "GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile HTTP/1.1" 403 14 "-" "Wget/1.14 (linux-gnu)" "-"
[pid: 14|app: 0|req: 11/17] 103.116.47.51 () {42 vars in 934 bytes} [Sat Mar 27 14:43:38 2021] GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile => generated 14 bytes in 0 msecs (HTTP/1.1 403) 2 headers in 86 bytes (1 switches on core 0)
103.116.47.51 - - [27/Mar/2021:14:43:38 +0000] "GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile HTTP/1.1" 403 14 "http://140.238.4.243/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"

**Comment by hunshcn** [comment]
> 更新了你的docker镜像后
> raw 链接提示 403 错误 和 Invalid input.
> http://140.238.4.243/https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile
> 
> [pid: 15|app: 0|req: 6/14] 103.116.47.51 () {42 vars in 928 bytes} [Sat Mar 27 14:42:04 2021] GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile => generated 14 bytes in 0 msecs (HTTP/1.1 403) 2 headers in 86 bytes (1 switches on core 0)
> [pid: 14|app: 0|req: 9/15] 103.116.47.51 () {44 vars in 829 bytes} [Sat Mar 27 14:42:04 2021] GET /favicon.ico => generated 3262 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
> 103.116.47.51 - - [27/Mar/2021:14:42:04 +0000] "GET /favicon.ico HTTP/1.1" 200 3262 "http://140.238.4.243/https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
> [pid: 14|app: 0|req: 10/16] 103.116.47.51 () {34 vars in 524 bytes} [Sat Mar 27 14:42:20 2021] GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile => generated 14 bytes in 0 msecs (HTTP/1.1 403) 2 headers in 86 bytes (1 switches on core 0)
> 103.116.47.51 - - [27/Mar/2021:14:42:20 +0000] "GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile HTTP/1.1" 403 14 "-" "Wget/1.14 (linux-gnu)" "-"
> [pid: 14|app: 0|req: 11/17] 103.116.47.51 () {42 vars in 934 bytes} [Sat Mar 27 14:43:38 2021] GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile => generated 14 bytes in 0 msecs (HTTP/1.1 403) 2 headers in 86 bytes (1 switches on core 0)
> 103.116.47.51 - - [27/Mar/2021:14:43:38 +0000] "GET /https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile HTTP/1.1" 403 14 "http://140.238.4.243/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"

佛了，历史遗留问题，最早都是g开头的网址
我觉得得上ci test了

**Comment by stilleshan** [comment]
高效..我在去测试下
