### ISSUE TITLE
Linux服务器上wget curl 的raw文件乱码?

### ISSUE THREAD

**Issue by stilleshan** [hunshcn/gh-proxy#32]
测试了web端下载raw的文件没问题
但是服务器上wget和curl下来的就是乱码...

**Comment by stilleshan** [comment]
https://ghproxy.com
大佬测试下看看

**Comment by stilleshan** [comment]
测试地址
http://140.238.4.243/https://raw.githubusercontent.com/stilleshan/ServerStatus/master/Dockerfile

<img width="697" alt="截屏2021-03-29 10 16 58" src="https://user-images.githubusercontent.com/22582966/112778815-f45a5200-9077-11eb-9edc-afd153b2e510.png">

**Comment by hunshcn** [comment]
问题的原因是curl不会添加`accept-encoding`的header，请求到达python的时候，我们使用requests发送请求，requests对header的`accept`、`accept-encoding`、`user-agent`、`Connection`进行了默认值的处理，所以github返回了压缩后的内容，导致乱码。

https://github.com/hunshcn/gh-proxy/commit/9b1d1f1155720f1f1e9e64d347113dbd35395fce 给requests打上了monkey patch，把默认headers给清空了。这下应该就没问题了。

**Comment by stilleshan** [comment]
好的,正好准备来测试下.感谢
