### ISSUE TITLE
支持 raw.github.com

### ISSUE THREAD

**Issue by mgzu** [hunshcn/gh-proxy#38]
`
例如 https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
`

**Comment by hunshcn** [comment]
已支持

**Comment by jejer** [comment]
看起来还不支持呢? 
https://gh.api.99988866.xyz/https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
404

**Comment by hunshcn** [comment]
> 看起来还不支持呢? https://gh.api.99988866.xyz/https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh 404

之前演示站忘记更新了，不过刚发现一个bug...已修复

**Comment by jejer** [comment]
> > 看起来还不支持呢? https://gh.api.99988866.xyz/https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh 404
> 
> 之前演示站忘记更新了，不过刚发现一个bug...已修复

没问题了 多谢~
