### ISSUE TITLE
使用python3部署后访问显示Invalid input.

### ISSUE THREAD

**Issue by 7iYe** [hunshcn/gh-proxy#39]
如题
    显示Invalid input，控制台显示403

本地配置
主机：macOS Big Sur 11.2.3
部署：Python 3.9.5
方向代理：nginx-1.19.10
hosts：127.0.0.1 githubproxy.com

![截屏2021-05-30 下午12 32 40](https://user-images.githubusercontent.com/30172295/120092122-46d0f100-c143-11eb-8a25-74663e9a02f8.png)

<img width="1590" alt="截屏2021-05-30 下午12 31 06" src="https://user-images.githubusercontent.com/30172295/120092090-07a2a000-c143-11eb-92db-6ff7af826477.png">

**Comment by hunshcn** [comment]
这个是因为
https://github.com/hunshcn/gh-proxy/blob/master/app/main.py#L93
把 `:/`替换成了`://`，所以导致 `https:///`的出现，把这行删去就行了

**Comment by 7iYe** [comment]
u = u.replace('s:/', 's://', 1)  # uwsgi会将//传递为/
是这一行吗？

**Comment by hunshcn** [comment]
之前在其他环境下，`//`都会传递为`/`，所以有L93的处理，这个情况不知道是不是mac系统下的不一致表现

**Comment by hunshcn** [comment]
> u = u.replace('s:/', 's://', 1) # uwsgi会将//传递为/
> 是这一行吗？

是的

**Comment by 7iYe** [comment]
可以了，可是下载速度有点慢是什么情况
这是与演示地址下载速度点对比

![截屏2021-05-30 下午12 46 25](https://user-images.githubusercontent.com/30172295/120092409-18541580-c145-11eb-9d13-473048dbace0.png)

**Comment by hunshcn** [comment]
url处理问题可以稍等一下，我打个补丁
速度慢是因为本机访问本来就慢...
需要一台访问github速度快的服务器来部署他

**Comment by 7iYe** [comment]
嗯，是网络原因，有时是KB/s，有时可以达到M/s。
