### ISSUE TITLE
能否请教下clone的用法呢

### ISSUE THREAD

**Issue by SKIYET** [hunshcn/gh-proxy#4]
尊敬的开发者：

你好！

能否请教下clone的命令应该怎么写呢

**Comment by hunshcn** [comment]
git clone https://gh.api.99988866.xyz/github.com/abc/abc
不支持git://因为那个是走ssh

**Comment by SKIYET** [comment]
> 
> 
> git clone https://gh.api.99988866.xyz/github.com/abc/abc
> 不支持git://因为那个是走ssh

明白了！谢谢！
