### ISSUE TITLE
docker部署的怎么能支持git clone?

### ISSUE THREAD

**Issue by stilleshan** [hunshcn/gh-proxy#5]
求教如何支持 git clone

**Comment by hunshcn** [comment]
跟js版本一样是git clone http://你的域名:port/github.com/hunshcn/gh-proxy.git
一样不支持git://，因为会需要22端口

**Comment by stilleshan** [comment]
出现错误
error: RPC failed; result=22, HTTP code = 405
fatal: The remote end hung up unexpectedly

我是docker部署,反代到443

git clone https://xxxx.xxxx.com/github.com/hunshcn/gh-proxy.git

**Comment by stilleshan** [comment]
还有,如果打算走服务器流量,是不是 -v 挂载 main.py 到/app/main.py
修改
jsdelivr = 0
cnpmjs = 0

**Comment by hunshcn** [comment]
错误原因我就不太清楚了，可以先试试http走暴露出来的端口，可能问题在反代上，我刚用自己的机器试过没有问题。

修改配置是的

**Comment by stilleshan** [comment]
放开端口,直接走http也是这个错误...

**Comment by stilleshan** [comment]
jsdelivr = 0
cnpmjs = 0
这2个参数只是负责git的,还是说直接下载文件也是走cdn?

**Comment by hunshcn** [comment]
jsdelivr是文件
cnpmjs是git

我怀疑问题可能是因为py版本没有处理post请求吧，虽然之前的测试clone过程都是不存在post的，待我尝试复现一下

**Comment by stilleshan** [comment]
谢谢大佬.

**Comment by hunshcn** [comment]
抱歉之前测试没做好，问题确实是没处理POST请求，新版本已经修复了

**Comment by stilleshan** [comment]
大佬牛逼..已搞定..好用.
