### ISSUE TITLE
请问可以写一个python部署教程吗？

### ISSUE THREAD

**Issue by zhouguangyou1994** [hunshcn/gh-proxy#54]
请问可以写一个python部署教程吗？

**Comment by hunshcn** [comment]
```shell
cd app
pip install flask requests
uwsgi --ini ./uwsgi.ini
```
不过也要自己用systemd/supervisor或者其他进程管理工具配置一下。

然后nginx/apache反代一下以加上https就行（如果没有前端服务器可能会有问题，不太确定）。


如果上面说的听得有点迷茫，说明直接部署不适合你...用docker就好了，readme有

程序应该部署在可以直连github的服务器上

**Comment by qzdf** [comment]
> ```shell
> cd app
> pip install flask requests
> uwsgi --ini ./uwsgi.ini
> ```
> 
> 不过也要自己用systemd/supervisor或者其他进程管理工具配置一下。
> 
> 然后nginx/apache反代一下以加上https就行（如果没有前端服务器可能会有问题，不太确定）。
> 
> 如果上面说的听得有点迷茫，说明直接部署不适合你...用docker就好了，readme有
> 
> 程序应该部署在可以直连github的服务器上

但是docker部署的版本好像不支持，黑白名单
