### ISSUE TITLE
貌似 github.com.cnpmjs.org 停止解析了?

### ISSUE THREAD

**Issue by stilleshan** [hunshcn/gh-proxy#57]
突然发现 github.com.cnpmjs.org 域名貌似是停止解析了? 暂停提供cdn了么? 有没有知道的.

**Comment by Silentely** [comment]
应该停掉了, 把cnpmjs参数改为0

**Comment by Awei2020** [comment]
github.com.cnpmjs.org一样无法用 怎么办呢

**Comment by hunshcn** [comment]
![image](https://user-images.githubusercontent.com/11679819/154089683-0b228566-7fb0-4327-92b6-9344c3b93c61.png)
已停止服务
