### ISSUE TITLE
移除cnpmjs github后，clone加速没了么？

### ISSUE THREAD

**Issue by zhuiyue132** [hunshcn/gh-proxy#58]
我按照教程部署一遍，发现clone不了。
![image](https://user-images.githubusercontent.com/26954775/154277125-2c67a4ad-fc7a-4ac8-9d19-ced19e661a31.png)

**Comment by hunshcn** [comment]
![image](https://user-images.githubusercontent.com/11679819/154277535-ab62afb6-9a31-43ae-9b48-98a766c8f641.png)

检查自己到worker的链路，项目没有问题
