### ISSUE TITLE
拉jd的仓库会失败，拉取其他的都没有问题

### ISSUE THREAD

**Issue by Vanuty** [hunshcn/gh-proxy#61]

**Comment by cdlaimin** [comment]
青龙面板? 那个默认的代理是屏蔽了jd的地址不能下

**Comment by Vanuty** [comment]
> 请教一下大佬有没有办法能解除自建代理的屏蔽

**Comment by cdlaimin** [comment]
> > 请教一下大佬有没有办法能解除自建代理的屏蔽

将默认的代理换成这个自建的, 我试过了可以的

**Comment by Vanuty** [comment]
> > > 请教一下大佬有没有办法能解除自建代理的屏蔽
> 
> 将默认的代理换成这个自建的, 我试过了可以的

感谢
