### ISSUE TITLE
求助，我也搭建了一个cloudflare的版本，网速没你快

### ISSUE THREAD

**Issue by Stonewalling** [hunshcn/gh-proxy#62]
大佬能不能分享下，你是如何下载很快的，我搭建的cloudflare的版本下载速度在100多kb,但是用你的演示链接能在2M/s

**Comment by hunshcn** [comment]
演示站没有特殊配置，通过partner接入

**Comment by Stonewalling** [comment]
> 演示站没有特殊配置，通过partner接入

这个partner是什么程序啊，我找了几次没找对

**Comment by hunshcn** [comment]
比如这个
https://wzfou.com/cloudflare-partner/
