### ISSUE TITLE
二级目录下提交下载地址, 会被跳转至一级目录下的下载地址. 

### ISSUE THREAD

**Issue by orangejx** [hunshcn/gh-proxy#63]
老板, 二级目录下提交 `Github` 地址似乎还是会被跳转至一级目录的下载地址, 例如: 在 `https://hunshcn.github.io/gh-proxy/` 提交下载地址( `https://github.com/hunshcn/gh-proxy/archive/refs/heads/master.zip` ), 会跳转至 `https://hunshcn.github.io/https://github.com/hunshcn/gh-proxy/archive/refs/heads/master.zip` , 而不是相对应的 `https://hunshcn.github.io/gh-proxy/https://github.com/hunshcn/gh-proxy/archive/refs/heads/master.zip` , 在 workers 里修改了 prefix 之后也没有变化.

PS: `之前在您博客下面尝试留言, 但是好像有 200 字的字数限制, 修改了几次依然还是超过 200 字, 只能发个 issue 了 😂`

**Comment by hunshcn** [comment]
嗯之前前端没考虑到这个，已经加上自动判断了
