### ISSUE TITLE
docker搭建一直报502

### ISSUE THREAD

**Issue by firesky123** [hunshcn/gh-proxy#67]
docker搭建了一直报502 bad gateway，反代不行，直接用ip加端口访问也不行，是啥情况呀。

**Comment by hunshcn** [comment]
![image](https://user-images.githubusercontent.com/11679819/162578483-f102a19a-e6c7-4c12-9553-81bb362091dc.png)
找了台机器，没有问题。

你的服务器在大陆？需要保证与github.com的连接没有问题

**Comment by firesky123** [comment]
那我再换一台机器试一试，机器在海外，本身也能访问github，但是服务不通。
