### ISSUE TITLE
甲骨文无法安装

### ISSUE THREAD

**Issue by leave668** [hunshcn/gh-proxy#73]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
9092dc3a3b509a37853ff6adf26bf1e0e5a1ffe3fb4baa0e4993a26a6ddff170
docker: Error response from daemon: driver failed programming external connectivity on endpoint gh-proxy-py (f0212303e6b88c434808b34ef0883726d68e71adc5d5f6a0e5218ba6720e9eb7): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.

**Comment by hunshcn** [comment]
基础镜像是amd64的，可以换amd实例来运行

或者自己改一下dockerfile的基础镜像到 guysoft/uwsgi-nginx:python3.7

带头大哥纯洁 ***@***.***> 于2022年5月12日周四 11:15写道：

**Comment by hunshcn** [comment]
已支持
