### ISSUE TITLE
建议加上下载文件大小限制

### ISSUE THREAD

**Issue by hiCasper** [hunshcn/gh-proxy#8]
如果需要中转的文件大小较大，有可能长时间消耗服务器网络资源，可以在配置中加上文件大小限制，超出则返回原url。

**Comment by hunshcn** [comment]
https://github.com/hunshcn/gh-proxy/commit/b9ce7958181aa28da76c92e1542c9979eb2e7d13 已增加

**Comment by yesusman300-dot** [comment]
From gtts import gTTS``
