### ISSUE TITLE
部署到cf-worker上不可用提示blocked

### ISSUE THREAD

**Issue by sxsjs123** [hunshcn/gh-proxy#80]
![image](https://user-images.githubusercontent.com/31535751/180634527-5c25b565-b8d7-4ffd-b737-6b46f2ddf636.png)
如图 麻烦大佬解答

**Comment by hunshcn** [comment]
昨天修出了一个bug。。。使用新的内容部署

**Comment by sxsjs123** [comment]
你好重新部署后还是同样问题

**Comment by sxsjs123** [comment]
你好重新开了一个 部署成功    cloudflare缓存问题导致  谢谢大大
