### ISSUE TITLE
一个仓库克隆失败

### ISSUE THREAD

**Issue by lglgdouble** [hunshcn/gh-proxy#81]
cyc@ZCG04000351:~$ git clone https://ghproxy.com/https://github.com/nlohmann/json.git
Cloning into 'json'...
fatal: repository 'https://ghproxy.com/https://github.com/nlohmann/json.git/' not found
cyc@ZCG04000351:~$

**Comment by stilleshan** [comment]
我也测试提示404, 测试这个 nlohmann 的其他仓库没问题.
会不会是 json 这个关键词的问题? 等作者来看看...

**Comment by stilleshan** [comment]
刚创建个叫 json 的仓库也提示 404
```
root@debian11:~# git clone https://ghproxy.com/https://github.com/stilleshan/json
正克隆到 'json'...
fatal: 仓库 'https://ghproxy.com/https://github.com/stilleshan/json/' 未找到
```

**Comment by hunshcn** [comment]
@stilleshan 我本地起一个新环境是没问题的，也不应该有问题，检查下pass by 配置？

**Comment by stilleshan** [comment]
刚才在本地 ip:端口 来代理是可以的.
但是前端套了nginx反代就报404错误.但是检查nginx配置并没有什么特殊配置
