### ISSUE TITLE
小建议：支持搜索功能

### ISSUE THREAD

**Issue by Uber-Eins** [hunshcn/gh-proxy#82]
将ASSET_URL改为git做完全镜像时，使用搜索时会直接转到**/【输入搜索框的内容】，而正常的搜索应该是**/search?q=【输入搜索框的内容】

**Comment by hunshcn** [comment]
感觉意义不大，最早是/?q=，但是后来发现param必须得符合urlencode，对命令行支持极其不友好。做两个endpoint又比较麻烦，所以是现在这个情况。通过前端访问的比重应该不大，更多的应该是直接输入网址/命令行/程序

**Comment by daiaji** [comment]
确实感觉/?q=屁用没用，限制多，同方案的也少。感觉可以直接移除。
