### ISSUE TITLE
cf worker报错

### ISSUE THREAD

**Issue by RookieTerry** [hunshcn/gh-proxy#89]
如题，我使用了cloudflare worker部署，使用生成的`workers.dev`域名访问出现1042错误码，在自有域名开启workers路由后访问自有域名出现1000错误码，请问是什么原因导致的？使用自有域名的`index.js`配置如下：
![image](https://user-images.githubusercontent.com/77920425/202898476-c719f1c7-f683-4318-b1f1-a375844cb399.png)

**Comment by hunshcn** [comment]
ASSET_URL是你的加速域名？这样死循环了，改回去吧。

**Comment by RookieTerry** [comment]
这个是我自己的域名。那URL后面还需要加上`/gh-proxy/`吗？

**Comment by bebestmaple** [comment]
目前在cf worker 的预览中可以正常展示，但直接访问时cf提示 Error 1101，请问是什么问题？
