### ISSUE TITLE
Cloudflare Workers搭建的老是访问不了怎么办

### ISSUE THREAD

**Issue by aprilz-code** [hunshcn/gh-proxy#91]
![image](https://user-images.githubusercontent.com/33222816/206726347-6217a8b3-ca79-473a-a0a8-7eb11ddde8de.png)
很多时间段就是访问就是  该网页无法正常运作

**Comment by hunshcn** [comment]
绑定自有域名会有缓解

**Comment by aprilz-code** [comment]
好的,谢谢大佬
