### ISSUE TITLE
能否出一个可以用github pages部署的版本？

### ISSUE THREAD

**Issue by fjqz177** [hunshcn/gh-proxy#94]
cf worker太慢了，如果有github pages的版本的话，就可以用cf pages部署了，那样就很快

**Comment by hyyxiaoluo** [comment]
作者的page开了，我试着也fork开page但是显示的跟作者不一样，不知道作者咋用page部署的，我部署完打开显示的是md文档的东西

**Comment by hyyxiaoluo** [comment]
哦哦，我才看到你的分支，作者你的page运行的是html那个网页是吧，现在我是work运行成功了，但是完全就是没有加速的感觉，复制github链接下载网站一直转就是不弹下载最后不了了之，这加速原则是啥啊，是不是只有自己在服务器自己搭建，走服务器的节点才能加速访问？人家的博主搭建的我不开梯子就能下载，我的不开梯子就下载不了，开了才能弹出来链接

**Comment by hunshcn** [comment]
> 哦哦，我才看到你的分支，作者你的page运行的是html那个网页是吧，现在我是work运行成功了，但是完全就是没有加速的感觉，复制github链接下载网站一直转就是不弹下载最后不了了之，这加速原则是啥啊，是不是只有自己在服务器自己搭建，走服务器的节点才能加速访问？人家的博主搭建的我不开梯子就能下载，我的不开梯子就下载不了，开了才能弹出来链接

默认的worker.dev域名被屏蔽，需要绑定自己的域名

**Comment by hyyxiaoluo** [comment]
感谢作者的解释，问题已解决，只是速度只有200k，我记录的网址有的能达到即使兆，这是什么原因呢，是他们有服务器好？

**Comment by hyyxiaoluo** [comment]
> > 哦哦，我才看到你的分支，作者你的page运行的是html那个网页是吧，现在我是work运行成功了，但是完全就是没有加速的感觉，复制github链接下载网站一直转就是不弹下载最后不了了之，这加速原则是啥啊，是不是只有自己在服务器自己搭建，走服务器的节点才能加速访问？人家的博主搭建的我不开梯子就能下载，我的不开梯子就下载不了，开了才能弹出来链接
> 
> 默认的worker.dev域名被屏蔽，需要绑定自己的域名

我想问下我创建完的速度很慢有时候还解析加载失败，但是我见有些博主自建的解析很快而且下载几十兆每秒，那是他们的服务器的原因么，国外服务器?我的诉求现在是不知道自己的是不是差在服务器上面了，是不是服务器本身访问GitHub就要很快还是什么？求大佬解惑
